### ISSUE TITLE
But after update to 3.0.0-preview.25 ?

### ISSUE THREAD

**Issue by KANekT** [martinothamar/Mediator#146]
after update from 3.0.0-preview.24 to 3.0.0-preview.25

I have error in rider and ci :
error CS1061: 'IServiceCollection' does not contain a definition for 'AddMediator' and no accessible extension method 'AddMediator' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

**Comment by KANekT** [comment]
after update Mediator.g.cs is deleted

return in 3.0.0-preview.24 Mediator.g.cs generate again

**Comment by KANekT** [comment]
```
    <PackageReference Include="Mediator.Abstractions" Version="3.0.0-preview.24" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.0-preview.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

**Comment by martinothamar** [comment]
Not able to reproduce with the testapps I have here. I found some places where the error handling isn't great. I'm publishing another preview to rectify that. 3.0.0-preview.26 should be published in a couple of minutes

Are you sure you are not seeing any more error messages? Even if the source generator just crashes, there should be some logging to indicate that, something like this:
![image](https://github.com/martinothamar/Mediator/assets/5425986/a6460159-4f7f-47c2-802c-2b406e5cfdc1)

In the meantime I'll update a larger application and see if I can provoke any issues

**Comment by KANekT** [comment]
35>CSC: Error MSG0000 : MediatorGenerator got unknown error while generating mediator implementation, please report this to the issue tracker on github at https://github.com/martinothamar/Mediator/issues/new . Error: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Comparison`1[System.Int32]'.:    at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
35

**Comment by martinothamar** [comment]
Great, that should do it, thank you! Will report back when it's fixed

**Comment by BC89** [comment]
I was using .25 and it didn't build, then moved to .26 after I saw you roll that out but still the same result. The code is from my GIT DIFF so that's why it showed both.

 OS - running on a windows hot but targeting docker for Linux.
.Net 8
Scoped service lifetime

Thx,
-BC


________________________________
From: Martin Othamar ***@***.***>
Sent: Monday, April 8, 2024 2:36 PM
To: martinothamar/Mediator ***@***.***>
Cc: Brendan Carroll ***@***.***>; Comment ***@***.***>
Subject: [External Email] Re: [martinothamar/Mediator] Bug after update to 3.0.0-preview.25 ? (Issue #146)

***From ***@***.*** 410-316-7820 *** This is an External Email from outside of KCI.***

________________________________
Strange! Just to double check, you were referencing 3.0.0-preview.26 for both packages right? Because one of the references above is 25, and I wouldn't expect that kind of difference from the change I made..

I just tried to upgrade some more apps, no issues.. Must be something about the configuration. Could you tell me more about environment and Mediator configuration?

  *   OS
  *   .NET version (SDK and tfm)
  *   AddMediator or the options attribute for configuration?
     *   Which ServiceLifetime and have you configured a different namespace?

**Comment by KANekT** [comment]
> <PackageReference Include="Mediator.SourceGenerator" Version="3.0.0-preview.25">
>       <PrivateAssets>all</PrivateAssets>
>       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
>     </PackageReference>

Use 26 , not 25

**Comment by martinothamar** [comment]
I wasn't able to reproduce the exact error, but the comparer I had implemented was buggy for sure... #147

preview 27 should be out in a couple of minutes

**Comment by BC89** [comment]
That fixed it. Thanks,
Brendan

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Martin Othamar ***@***.***>
Sent: Monday, April 8, 2024 3:55:46 PM
To: martinothamar/Mediator ***@***.***>
Cc: Brendan Carroll ***@***.***>; Comment ***@***.***>
Subject: [External Email] Re: [martinothamar/Mediator] Bug after update to 3.0.0-preview.25 ? (Issue #146)


***From ***@***.*** 410-316-7820 *** This is an External Email from outside of KCI.***
________________________________
I wasn't able to reproduce the exact error, but the comparer I had implemented was buggy for sure... #147<https://github.com/martinothamar/Mediator/pull/147>

preview 27 should be out in a couple of minutes

**Comment by martinothamar** [comment]
Great, thanks!

**Comment by austins** [comment]
Preview 27 works great so far! Thank you!

**Comment by austins** [comment]
Reporting back after a couple months that the notification publisher feature is still working great with no issues. I'm using TaskWhenAllPublisher to dispatch various Discord bot events in prod. At one point, I had a custom notification publisher and that also worked without any issues. 😁

**Comment by frozzway** [comment]
For those who are using .NET 6 and still encountering this issue:

Changing MSBuild version from 9.0.107 to 6.0.136 fixed it for me.
